const baseUrl = 'http://192.168.1.12:8080'
const gptUrl = 'http://13.93.229.87:8899'

const gpttoken = 'sk-RPsa5iOX6J0NHDyVBbCe0e01F42f44FfA34069BbB17fA326'
const testtoken = 'eyJhbGciOiJIUzUxMiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_x2L0QrDIAxF_yXPFeLUmPVvlEZqoSDEwsbYvzfb2z2cez5wzA4rSCWMgavz-Cgukm_uiYldy6nmrTEiCyzQy4TVZ58pJvZxAb2q1frWKefPqxru0s9iVK7NqIxhW17jX1pFkdiu5kL43mg3vxaBAAAA.fUT3IabNO_n2yxTNSC44_uD_5rkIJhJjr8RN8TaTq_h26-iT-X1LX2zNCrdHz_awDfcHdE4E5v9gvakC04k00g'

const likeimage = $r('app.media.like')
const like1image = $r('app.media.like1')
const favoriteimage = $r('app.media.favorite')
const favorite1image = $r('app.media.favorite1')
const searchimage = $r('app.media.search')
const hotimage = $r('app.media.hot')
const backimage = $r('app.media.back')
const phtoimage = $r('app.media.phto')
const openaiimage = $r('app.media.openai')



export { baseUrl , testtoken,likeimage,favoriteimage,
  like1image,favorite1image,searchimage,hotimage,
  backimage,phtoimage,gptUrl,openaiimage,gpttoken
}