const baseUrl = 'http://192.168.31.196:8080'

const testtoken = "eyJhbGciOiJIUzUxMiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_yWLSwrDMAwF76J1DP5FcnIbGavUgYBBDrSU3j0q3b1h3nzgmB12WLGVII_kMKXmMjV2XENxEaP3K3HNSWCBzhP2QIEyEkW_gF7Van3rlPPnVQ2f0k824qsZ8Ri25TX-5YYlUbarufi9AW9VHySAAAAA.WIChsd3sVQkkv7Fg3YB3V1tNZhDM0Bq_SJM_Z1LiHmU-I2V9t75Uk89Q6n_pbYX_rRk3pOFv-M-mzXOYuZoWGg"


const likeimage = $r('app.media.like')
const like1image = $r('app.media.like1')
const favoriteimage = $r('app.media.favorite')
const favorite1image = $r('app.media.favorite1')
const searchimage = $r('app.media.search')
const hotimage = $r('app.media.hot')
const backimage = $r('app.media.back')



export { baseUrl , testtoken,likeimage,favoriteimage,
  like1image,favorite1image,searchimage,hotimage,
  backimage
}